### ISSUE TITLE
能否弄一个docker-compose，让开发者可以快速体验？

### ISSUE THREAD

**Issue by 0000005** [acgist/taoyao#2]
本来这套环境就很复杂，要是弄一个docker-compose，可以一键启动就方便了。可以让开发者快速尝鲜。
我看到部署文档中提到的使用docker启动 媒体服务器。
```shell
docker run --name="taoyao-client-media" -d acgist/taoyao-client-media:1.0.0
```
但是上面的启动命令并没有暴露任何端口出来，我不知道其他组件如何与 mediasoup 通讯呢？要怎么配置？

另外，我自己做了一个docker-compose.yml，但是也没跑起来。大佬可以帮忙看看吗？
```yml
version: '3'
services:
  taoyao-client-web:
    image: acgist/taoyao-client-web:1.0.0
    container_name: taoyao-client-web
    ports:
      - "8443:8443"
    restart: always

  taoyao-client-media:
    image: acgist/taoyao-client-media:1.0.0
    container_name: taoyao-client-media
    ports:
      - "40000-49999:40000-49999"
      - "42222:42222"
    environment:
      - MEDIASOUP_WORKER_SIZE=2
      - MEDIASOUP_MIN_PORT=40000
      - MEDIASOUP_MAX_PORT=49999
      - MEDIASOUP_LISTEN_IP=0.0.0.0
      - MEDIASOUP_LISTEN_PORT=42222
      - MEDIASOUP_ANNOUNCED_IP=90.1.0.222
    restart: always


  taoyao-signal-server:
    image: acgist/taoyao-signal-server:1.0.0
    container_name: taoyao-signal-server
    ports:
      - "8888:8888"
      - "9999:9999"
```

**Comment by acgist** [comment]
这个是旧版的镜像了，新的我没有制作了，直接使用主机网络，然后媒体服务需要配置地址：

```
version: "3.1"

services:

  taoyao-client-web:
    image: acgist/taoyao-client-web:1.0.0
    restart: always
    privileged: true
    network_mode: host
    container_name: taoyao-client-web
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=Asia/Shanghai

  taoyao-client-media:
    image: acgist/taoyao-client-media:1.0.0
    restart: always
    privileged: true
    network_mode: host
    container_name: taoyao-client-media
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./taoyao-client-media/Config.js:/data/taoyao/taoyao-client-media/src/Config.js
    environment:
      - TZ=Asia/Shanghai

  taoyao-signal-server:
    image: acgist/taoyao-signal-server:1.0.0
    restart: always
    privileged: true
    network_mode: host
    container_name: taoyao-signal-server
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=Asia/Shanghai
```

`Config.js`这个里面修改`192.168.1.100`这个IP地址

```
const os = require("os");

// 桃夭媒体服务地址
defaultTaoyaoHost = "192.168.1.100";
// defaultTaoyaoHost = "192.168.8.110";

/**
 * 配置
 */
module.exports = {
  // 服务名称
  name: "taoyao-client-media",
  // 信令配置
  signal: {
    // 服务版本
    version: "1.0.0",
    // 终端标识
    clientId: "taoyao-client-media",
    // 终端名称
    name: "桃夭媒体服务",
    // 地址
    // host: "127.0.0.1",
    host: "192.168.1.100",
    // host: "192.168.8.100",
    // 端口
    port: 8888,
    // 协议
    scheme: "wss",
    // 信令用户
    username: "taoyao",
    // 信令密码
    password: "taoyao",
  },
  // Mediasoup
  mediasoup: {
    // 配置Worker进程数量
    workerSize: Object.keys(os.cpus()).length,
    // Worker：https://mediasoup.org/documentation/v3/mediasoup/api/#WorkerSettings
    workerSettings: {
      // 记录标记
      logTags: [
        "bwe",
        "ice",
        "rtp",
        "rtx",
        "svc",
        "dtls",
        "info",
        "rtcp",
        "sctp",
        "srtp",
        "score",
        "message",
        "simulcast",
      ],
      // 级别：debug | warn | error | none
      logLevel: "warn",
      rtcMinPort: process.env.MEDIASOUP_MIN_PORT || 40000,
      rtcMaxPort: process.env.MEDIASOUP_MAX_PORT || 49999,
    },
    // Router：https://mediasoup.org/documentation/v3/mediasoup/api/#RouterOptions
    routerOptions: {
      mediaCodecs: [
        {
          kind: "audio",
          mimeType: "audio/opus",
          clockRate: 48000,
          channels: 2,
        },
        {
          kind: "video",
          mimeType: "video/VP8",
          clockRate: 90000,
          parameters: {
            "x-google-start-bitrate": 1000,
            // "x-google-min-bitrate": 800,
            // "x-google-max-bitrate": 1600,
          },
        },
        {
          kind: "video",
          mimeType: "video/VP9",
          clockRate: 90000,
          parameters: {
            "profile-id": 2,
            "x-google-start-bitrate": 1000,
            // "x-google-min-bitrate": 800,
            // "x-google-max-bitrate": 1600,
          },
        },
        {
          kind: "video",
          mimeType: "video/h264",
          clockRate: 90000,
          parameters: {
            "packetization-mode": 1,
            "profile-level-id": "4d0032",
            "level-asymmetry-allowed": 1,
            "x-google-start-bitrate": 1000,
            // "x-google-min-bitrate": 800,
            // "x-google-max-bitrate": 1600,
          },
        },
        {
          kind: "video",
          mimeType: "video/h264",
          clockRate: 90000,
          parameters: {
            "packetization-mode": 1,
            "profile-level-id": "42e01f",
            "level-asymmetry-allowed": 1,
            "x-google-start-bitrate": 1000,
            // "x-google-min-bitrate": 800,
            // "x-google-max-bitrate": 1600,
          },
        },
      ],
    },
    // WebRtcServer：https://mediasoup.org/documentation/v3/mediasoup/api/#WebRtcServerOptions
    webRtcServerOptions: {
      listenInfos: [
        // UDP
        {
          protocol: "udp",
          ip: process.env.MEDIASOUP_LISTEN_IP || "0.0.0.0",
          port: 44444,
          announcedIp: process.env.MEDIASOUP_ANNOUNCED_IP || defaultTaoyaoHost || "127.0.0.1",
        },
        // TCP
        {
          protocol: "tcp",
          ip: process.env.MEDIASOUP_LISTEN_IP || "0.0.0.0",
          port: 44444,
          announcedIp: process.env.MEDIASOUP_ANNOUNCED_IP || defaultTaoyaoHost || "127.0.0.1",
        },
      ],
    },
    // WebRtcTransport：https://mediasoup.org/documentation/v3/mediasoup/api/#WebRtcTransportOptions
    webRtcTransportOptions: {
      listenIps: [
        {
          ip: process.env.MEDIASOUP_LISTEN_IP || "0.0.0.0",
          announcedIp: process.env.MEDIASOUP_ANNOUNCED_IP || defaultTaoyaoHost || "127.0.0.1",
        },
      ],
      initialAvailableOutgoingBitrate: 1000000,
      minimumAvailableOutgoingBitrate: 600000,
      maxSctpMessageSize: 262144,
      maxIncomingBitrate: 1500000,
    },
    // PlainTransport：https://mediasoup.org/documentation/v3/mediasoup/api/#PlainTransportOptions
    plainTransportOptions: {
      listenIp: {
        ip: process.env.MEDIASOUP_LISTEN_IP || "0.0.0.0",
        announcedIp: process.env.MEDIASOUP_ANNOUNCED_IP || defaultTaoyaoHost || "127.0.0.1",
      },
      maxSctpMessageSize: 262144,
    },
  },
};
```

@0000005
